name: Pipeline Python

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Fazer checkout do código
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Instalar pytest
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Executar script Python
      run: python app.py

    - name: Executar testes
      run: pytest